---
title: "Stock Market - Simple Quant"
author: "Gaurav Gurjar"
date: "7/30/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading the data and practicing with libraries
```{r}
library(tidyquant) 
library(xts)       # working with extensible time series
library(quantmod)  # get stock prices; useful stock analysis function
library(rvest)     # web scraping
library(tidyverse) # ggplot2, purrr, dplyr, tidyr, readr, tibble
library(stringr)   # working with strings
library(forcats)   # working with factors
library(lubridate) # working with dates in tibbles / data frames
library(plotly)    # Interactive plots
library(corrplot)  # Visualize correlation plots
```

Reading and Summarizing multiple "*.txt" files
```{r}
# 
cryptocurrencies_folder <- "./data/cryptocurrencies/"
cryptocurrencies_folder_files_list <- list.files(path = cryptocurrencies_folder, pattern = "*.txt")
cryptocurrencies_data <- do.call("rbind",
                                  lapply(cryptocurrencies_folder_files_list, 
                                         function(x)
                                         read.table(paste(cryptocurrencies_folder, x, sep = ''),
                                                          header = TRUE,
                                                          stringsAsFactors = FALSE)))

View(cryptocurrencies_data)

currencies_major_folder <- "./data/currencies/major/"
currencies_major_folder_files_list <- list.files(path = currencies_major_folder, pattern = "*.txt")
currencies_major_folder_data <- do.call("rbind",
                                  lapply(currencies_major_folder_files_list,
                                         function(x)
                                           read.table(paste(currencies_major_folder, x, sep = ''),
                                                      header = TRUE,
                                                      stringsAsFactors = FALSE)))
#View(currencies_major_folder_data)

currencies_other_folder <- "./data/currencies/other/"
currencies_other_folder_files_list <- list.files(path = currencies_other_folder, pattern = "*.txt")
currencies_other_folder_data <- do.call("rbind",
                                        lapply(currencies_other_folder_files_list,
                                               function(x)
                                                 read.table(paste(currencies_other_folder, x, sep = ''),
                                                            header = TRUE,
                                                            stringsAsFactors = FALSE)))
#View(currencies_other_folder_data)
```