---
title: "Stock Market - Simple Quant"
author: "Gaurav Gurjar"
date: "7/30/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
# Loading the data and practicing with libraries
library(tidyquant)
library(reshape2)
library(openxlsx)
library(xts)       # working with extensible time series
library(quantmod)  # get stock prices; useful stock analysis function
library(rvest)     # web scraping
library(tidyverse) # ggplot2, purrr, dplyr, tidyr, readr, tibble
library(stringr)   # working with strings
library(forcats)   # working with factors
library(lubridate) # working with dates in tibbles / data frames
library(plotly)    # Interactive plots
library(corrplot)  # Visualize correlation plots

```

Read in Data

```{r}
# update this file path to point toward appropriate folder on your computer
cryptocurrencies_folder <- "./data/cryptocurrencies/"
cryptocurrencies_folder_files_list <- list.files(path = cryptocurrencies_folder, pattern = "*.txt")
# read in each .txt file in file_list and rbind them into a data frame called  
cryptocurrencies_data <- do.call("rbind",
                                  lapply(cryptocurrencies_folder_files_list, 
                                         function(x)
                                         read.table(paste(cryptocurrencies_folder, x, sep = ''),
                                                          header = TRUE,
                                                          stringsAsFactors = FALSE)))
#View(cryptocurrencies_data)
currencies_major_folder <- "./data/currencies/major/"
currencies_major_folder_files_list <- list.files(path = currencies_major_folder, pattern = "*.txt")
currencies_major_folder_data <- do.call("rbind",
                                  lapply(currencies_major_folder_files_list,
                                         function(x)
                                           read.table(paste(currencies_major_folder, x, sep = ''),
                                                      header = TRUE,
                                                      stringsAsFactors = FALSE)))
#View(currencies_major_folder_data)
currencies_other_folder <- "./data/currencies/other/"
currencies_other_folder_files_list <- list.files(path = currencies_other_folder, pattern = "*.txt")
currencies_other_folder_data <- do.call("rbind",
                                        lapply(currencies_other_folder_files_list,
                                               function(x)
                                                 read.table(paste(currencies_other_folder, x, sep = ''),
                                                            header = TRUE,
                                                            stringsAsFactors = FALSE)))
#View(currencies_other_folder_data)
indices_folder <- "./data/indices/"
indices_folder_files_list <- list.files(path = indices_folder, pattern = "*.txt")
indices_folder_data <- do.call("rbind",
                               lapply(indices_folder_files_list,
                                      function(x)
                                        read.table(paste(indices_folder, x, sep = ''),
                                                   header = TRUE,
                                                   stringsAsFactors = FALSE)))
#View(indices_folder_data)
stooq_stocks_indices_folder <- "./data/stooq stocks indices/"
stooq_stocks_indices_folder_files_list <- list.files(path = stooq_stocks_indices_folder, pattern = "*.txt")
stooq_stocks_indices_folder_data <- do.call("rbind",
                                            lapply(stooq_stocks_indices_folder_files_list,
                                                   function(x)
                                                     read.table(paste(stooq_stocks_indices_folder, x, sep =''),
                                                                header = TRUE,
                                                                stringsAsFactors = FALSE)))
#View(stooq_stocks_indices_folder_data)
```

# Clean Data

```{r}
clean.data <- function(df){
  df <- cbind(df,
              colsplit(df$X.TICKER...PER...DATE...TIME...OPEN...HIGH...LOW...CLOSE...VOL...OPENINT.,
                       ',',
                       names = c('ticker', 'per', 'date', 'time', 'open', 'high', 'low', 'close', 'vol', 'openInt'))) %>% 
        mutate(date = ymd(date),
               time = as.numeric(time),
               open = as.double(open),
               high = as.double(high),
               low = as.double(low),
               close = as.double(close)) %>%
        select(ticker, date, open, high, low, close)
  return(df)
}

cryptocurrencies_data <- clean.data(cryptocurrencies_data)
currencies_major_folder_data <- clean.data(currencies_major_folder_data)
currencies_other_folder_data <- clean.data(currencies_other_folder_data)
indices_folder_data <- clean.data(indices_folder_data)
stooq_stocks_indices_folder_data <- clean.data(stooq_stocks_indices_folder_data)
```

Calculation

```{r}
cryptocurrencies_data <- cryptocurrencies_data %>% 
  mutate(atr = ATR(cryptocurrencies_data[, c("high", "low", "close")], n = 14)) 

#View(cryptocurrencies_data)

currencies_major_folder_data <- currencies_major_folder_data %>%
  mutate(atr = ATR(currencies_major_folder_data[, c("high", "low", "close")], n = 14))

#View(currencies_major_folder_data)

currencies_other_folder_data <- currencies_other_folder_data %>%
  mutate(atr = ATR(currencies_other_folder_data[, c("high", "low", "close")], n = 14))

indices_folder_data <- indices_folder_data %>%
  mutate(atr = ATR(indices_folder_data[, c("high", "low", "close")], n = 14))

stooq_stocks_indices_folder_data <- stooq_stocks_indices_folder_data %>%
  mutate(atr = ATR(stooq_stocks_indices_folder_data[, c("high", "low", "close")], n = 14))
```

```{r}
View(cryptocurrencies_data)
View(currencies_major_folder_data)
View(currencies_other_folder_data)
View(indices_folder_data)
View(stooq_stocks_indices_folder_data)
```

Converting to CSVs

```{r}
#write.csv(cryptocurrencies_data, file = "./CSVs/cryptocurrencies_data.csv", row.names = FALSE)
#write.csv(currencies_major_folder_data, file = "./CSVs/currencies_major_folder_data.csv")
#write.csv(currencies_other_folder_data, file = "./CSVs/currencies_other_folder_data.csv")
#write.csv(indices_folder_data, file = "./CSVs/indices_folder_data.csv")
#write.csv(stooq_stocks_indices_folder_data, file = "./CSVs/stooq_stocks_indices_folder_data.csv")
```

Converting to XLSx
Ticker wise Splitting the dataframes
```{r}
#ticker_wise_cryptocurrencies_data <- cryptocurrencies_data %>%
#  split(f = cryptocurrencies_data$ticker)
#ticker_wise_indices_folder_data <- indices_folder_data %>%
#  split(f = indices_folder_data$ticker)
#ticker_wise_stooq_stocks_indices_folder_data <- stooq_stocks_indices_folder_data %>%
#  split(f = stooq_stocks_indices_folder_data$ticker)
ticker_wise_currencies_major_folder_data <- currencies_major_folder_data %>%
  split(f = currencies_major_folder_data$ticker)
#View(ticker_wise_currencies_major_folder_data)
ticker_wise_currencies_other_folder_data <- currencies_other_folder_data %>%
  split(f = currencies_other_folder_data$ticker)
View(ticker_wise_currencies_other_folder_data)

write.xlsx(ticker_wise_currencies_major_folder_data, file = "./xlsx/ticker_wise_currencies_major_folder_data.xlsx")

write.xlsx(ticker_wise_currencies_other_folder_data, file = "./xlsx/ticker_wise_currencies_other_folder_data.xlsx")

write.xlsx(cryptocurrencies_data, file = "./xlsx/cryptocurrencies_data.xlsx")
#write.xlsx(currencies_major_folder_data, file = "./xlsx/currencies_major_folder_data.xlsx")
#write.xlsx(currencies_other_folder_data, file = "./xlsx/currencies_other_folder_data.xlsx")
write.xlsx(indices_folder_data, file = "./xlsx/indices_folder_data.xlsx")
write.xlsx(stooq_stocks_indices_folder_data, file = "./xlsx/stooq_stocks_indices_folder_data.xlsx")
```

```{r}
#path = "./xlsx/currencies_other_folder_data.xlsx"
#path %>% readxl::excel_sheets() %>% set_names() %>% purrr::map(Shee, path = path)
write.csv(cryptocurrencies_data, file = "./CSVs/cryptocurrencies_data.csv")
write.csv(currencies_major_folder_data, file = "./CSVs/currencies_major_folder_data.csv")
write.csv(currencies_other_folder_data, file = "./CSVs/currencies_other_folder_data.csv")
write.csv(indices_folder_data, file = "./CSVs/indices_folder_data.csv")
write.csv(stooq_stocks_indices_folder_data, file = "./CSVs/stooq_stocks_indices_folder_data.csv")
```
